### PR TITLE
empty project created

### PR DESCRIPTION
**Pull request by AlexandrGashevsky**

### CODE REVIEW

**Review by NazariiHRZ — APPROVED** [review]
Simple nack code

**Review by Nickwerat — APPROVED** [review]
Done.

**Comment by h4sq** [comment]
checked.

**Review by h4sq — APPROVED** [review]
checked.

**Comment by yu-ger** [comment]
good.

**Review by yu-ger — APPROVED** [review]

**Comment by santekhnik** [comment]
- [x] Please create separate folder called something like "PC application" and move this project there.
So in future everything related to this application will be located there

**Comment by NazariiHRZ** [comment]
Merge files for DEMO preparation

**Pull request merged**
